jobs:
  include:
    - arch: amd64
      dist: xenial
    - arch: amd64
      dist: bionic
    - arch: amd64
      dist: focal
    - arch: amd64
      dist: jammy
    # - arch: s390x
    #   dist: bionic
    # - arch: arm
    #   dist: bionic
    # - arch: ppc64le
    #   dist: bionic
   

language: python
python:
  - "2.7"
  
script:
  - uname -a
  - python3 --version
  - python --version
